version: "2.1"

services:
  query-runner:
    image: postgres
    env_file: query_runner.env
    volumes:
      - ./query.sql/:/opt/query.sql
      - ./test_query.sh/:/opt/test_query.sh
    networks:
      - advanced-databases_dvd_rental_network
    command: /bin/bash /opt/test_query.sh

networks:
  advanced-databases_dvd_rental_network:
    external: true
