version: "2.1"

services:
  database:
    container_name: dvd_rental_db
    build:
      context: postgis
    ports:
      - 5432:5432
    environment:
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks: 
      - rentals_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  rentals_network: