version: "2.1"

services:
  query-runner:
    image: postgres
    environment:
      - PGPASSWORD=password
    volumes:
      - ./:/opt/dvdrental
    networks:
      - advanced-databases_dvd_rental_network
    command: psql -h dvd_rental_db -p 5432 -U postgres -d dvdrental -w -a -f /opt/dvdrental/query.sql

networks:
  advanced-databases_dvd_rental_network:
    external: true
