version: "2.1"
# using 2.1 here allows for easy health-check syntax
# bumping to 3.X would require implementing manual health checking in the migrator

services:
  database:
    container_name: dvd_rental_db
    image: postgres
    ports:
      - 5432:5432
    env_file: dvd_rental_db.env
    networks:
      - dvd_rental_network
    mem_limit: 300m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    image: postgres
    environment:
      - PGPASSWORD=password
    volumes:
      - ./migrator_volume:/opt/dvdrental
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dvd_rental_network
    command: /bin/bash /opt/dvdrental/restore.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: dvd_rental_pgadmin
    ports:
      - 5430:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - dvd_rental_network

networks:
  dvd_rental_network:
