version: "2.1"

services:
  migrator:
    image: postgis/postgis
    privileged: true
    environment:
      - PGPASSWORD=password
    volumes:
      - ./migrator_volume:/migrator_volume
    networks:
      - advanced-databases_rentals_network
    command: bash -c "psql -h dvd_rental_db -p 5432 -U postgres -w -a -f /migrator_volume/restore.sql && sh /migrator_volume/restore.sh"

  geographer:
    image: osgeo/gdal:alpine-small-latest
    privileged: true
    volumes:
      - ./migrator_volume:/migrator_volume
    networks:
      - advanced-databases_rentals_network
    command: sh /migrator_volume/restore.sh
    
  geography-linker:
    image: postgis/postgis
    privileged: true
    environment:
      - PGPASSWORD=password
    volumes:
      - ./migrator_volume:/migrator_volume
    networks:
      - advanced-databases_rentals_network
    command: bash -c "psql -h dvd_rental_db -p 5432 -U postgres -w -a -f /migrator_volume/link_geography.sql"

networks:
  advanced-databases_rentals_network:
    external: true
