version: "2.1"

services:
  query_runner:
    image: postgres
    environment:
      - NUM_TESTS=10
      - PGPASSWORD=password
    volumes:
      - ./:/dvdrental
    networks:
      - advanced-databases_dvd_rental_network
    command: /bin/bash /dvdrental/test_query_using_time_diff.sh
    # command: /bin/bash /dvdrental/test_query_using_explain.sh

networks:
  advanced-databases_dvd_rental_network:
    external: true
