version: "2.1"

services:
  query_runner:
    image: query_runner
    build:
      context: container_build
    environment:
      - NUM_TESTS=10
      - PGPASSWORD=password
    volumes:
      - ./:/dvdrental
    networks:
      - advanced-databases_dvd_rental_network

networks:
  advanced-databases_dvd_rental_network:
    external: true
