version: "2.1"

services:
  query_runner:
    image: query_runner
    build:
      context: container_build
    environment:
      - DB_HOSTNAME=dvd_rental_db
      - DB_USER=postgres
      - DB_PASSWORD=dvd_rental_db
      - DB_DATABASE_NAME=dvdrental
      - DB_QUERY_FILE=/dvdrental/query.sql
      - DB_NUM_TESTS=10
    volumes:
      - ./:/dvdrental
    networks:
      - advanced-databases_dvd_rental_network

networks:
  advanced-databases_dvd_rental_network:
    external: true
